[project]
name = "selenium-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "colorlog>=6.9.0",
    "python-dotenv>=1.0.1",
    "selenium>=4.29.0",
    "undetected-chromedriver>=3.5.5",
]
